INSERT INTO public.survey_answer (id, question_id, value) VALUES (1, 1, 'Yoda');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (2, 1, 'Vader');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (3, 2, 'Princess Leia');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (4, 2, 'Luke Skywalker');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (5, 3, 'Han Solo');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (6, 3, 'Chewbacca');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (8, 5, 'Meat');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (9, 5, 'Veggies');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (10, 6, 'Orange');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (11, 6, 'Apple');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (12, 7, 'Sirloin');
INSERT INTO public.survey_answer (id, question_id, value) VALUES (13, 7, 'Sushi');